-- 001_init.sql — initial MyPA schema.
-- Generated retroactively from Base.metadata.create_all() output (2026-05-21).
-- DO NOT edit this file; add new migrations as 002_*.sql etc.

CREATE TABLE IF NOT EXISTS items (
    id           INTEGER PRIMARY KEY,
    kind         VARCHAR(64)  NOT NULL,
    title        VARCHAR(500) NOT NULL,
    body         TEXT NOT NULL DEFAULT '',
    status       VARCHAR(32)  NOT NULL DEFAULT 'open',
    priority     INTEGER      NOT NULL DEFAULT 3,
    due_at       DATETIME,
    tags         VARCHAR(500) NOT NULL DEFAULT '',
    data         JSON         NOT NULL DEFAULT '{}',
    source       VARCHAR(64)  NOT NULL DEFAULT 'manual',
    source_ref   VARCHAR(255),
    created_at   DATETIME     NOT NULL,
    updated_at   DATETIME     NOT NULL,
    completed_at DATETIME
);
CREATE INDEX  IF NOT EXISTS idx_items_kind_status ON items(kind, status);
CREATE INDEX  IF NOT EXISTS idx_items_due         ON items(due_at);
CREATE INDEX  IF NOT EXISTS ix_items_kind         ON items(kind);
CREATE UNIQUE INDEX IF NOT EXISTS uq_items_source_ref ON items(source, source_ref);

CREATE TABLE IF NOT EXISTS reminders (
    id       INTEGER PRIMARY KEY,
    item_id  INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    fire_at  DATETIME NOT NULL,
    fired_at DATETIME,
    channel  VARCHAR(32) NOT NULL DEFAULT 'telegram',
    message  TEXT
);
CREATE INDEX IF NOT EXISTS idx_reminders_due ON reminders(fire_at);
CREATE INDEX IF NOT EXISTS ix_reminders_item_id ON reminders(item_id);

-- Internal: track which migrations have been applied.
CREATE TABLE IF NOT EXISTS schema_versions (
    filename   TEXT PRIMARY KEY,
    applied_at DATETIME NOT NULL DEFAULT (datetime('now'))
);
